kernel:
  # Choose your kernel
  image: "linuxkit/kernel:4.11.x_dbg"
  # image: "linuxkit/kernel:4.11.x"
  # image: "linuxkit/kernel:4.10.x"
  # image: "linuxkit/kernel:4.9.x"
  # image: "linuxkit/kernel:4.4.x"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
  - linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
  - linuxkit/containerd:b50181bc6e0084e5fcd6b6ad3cf433c4f66cae5a
  - hvtest-local
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
services:
  - name: rngd
    image: "linuxkit/rngd:1fa4de44c961bb5075647181891a3e7e7ba51c31"
trust:
  org:
    - linuxkit
