kernel:
  # Choose your kernel
  image: "linuxkit/kernel:4.11.x"
  # image: "linuxkit/kernel:4.10.x"
  # image: "linuxkit/kernel:4.9.x"
  # image: "linuxkit/kernel:4.4.x"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:deea956a9ab07bf262083e93a86930bdc610cc2f
  - linuxkit/runc:2649198589ef0020d99f613adaeda45ce0093a38
  - linuxkit/containerd:cf2614f5a96c569a0bd4bd54e054a65ba17d167f
  - hvtest-local
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:1f5ec5d5e6f7a7a1b3d2ff9dd9e36fd6fb14756a"
    net: host
    pid: host
    ipc: host
    capabilities:
     - CAP_SYS_ADMIN
    readonly: true
services:
  - name: rngd
    image: "linuxkit/rngd:61a07ced77a9747708223ca16a4aec621eacf518"
    capabilities:
     - CAP_SYS_ADMIN
    oomScoreAdj: -800
    readonly: true
trust:
  image:
    - linuxkit/kernel
    - linuxkit/rngd
outputs:
  - format: kernel+initrd
  - format: iso-efi
